### ISSUE TITLE
Latest version of Qunit and latest version of sinon do not mix

### ISSUE THREAD

**Issue by dtracers** [qunitjs/qunit#1196] opened 2017-06-11 19:36 UTC
It seems they do not mix well because the documentation for Qunit with sinon does not even exist anymore

**Comment by trentmwillis** [comment] 2017-06-13 15:14
Can you explain what you mean by "do not mix"? Please provide what you are expecting to happen and what is actually happening. Also, a simplified reproduction (such as through JSBin) of your issue would be greatly appreciated.

In general, Sinon and QUnit are totally independent of each other so upgrading one should not affect the other as far as I am aware.

**Comment by trentmwillis** [comment] 2017-07-06 03:20
Closing this since it is not currently actionable. If a specific issue and reproduction can be provided, then feel free to reopen.

**Closed by trentmwillis** 2017-07-06 03:20 UTC
Labels: support
