### ISSUE TITLE
Too verbose reporting?

### ISSUE THREAD

**Issue by loldrup** [qunitjs/qunit#1300] opened 2018-08-01 07:35 UTC
When comparing two non-equal objects that have the same prototype chain, it seems unnecessary to report all the properties that reside on their prototype chain. This because we can know a priori that the difference between the two objects won't be found in their prototype object.
This behavior discourages test driven development, as having several failing tests quickly result in insurmountable amounts of lines being logged. Generating all that HTML slows down the browser.

This issue has two legs:
a. Should the `Diff`-section log all prototypal properties when we know that the difference between the objects can't reside among the prototypal properties?
b. Should qUnit log all prototypal properties when logging an object?

Example:
`a.deepEqual( new THREE.Vector3(1,2,3), new THREE.Vector3(2,3,4), "Bare bone test of excessive logging of prototype properties" );`

This test gives this output:

<details>
<pre>
Bare bone test of prototype comparison@ 80 ms
Expected: 	
{
  "add": function add( a, b ){
    [code]
  },
  "addScalar": function addScalar( a ){
    [code]
  },
  "addScaledVector": function addScaledVector( a, b ){
    [code]
  },
  "addVectors": function addVectors( a, b ){
    [code]
  },
  "angleTo": function angleTo( a ){
    [code]
  },
  "applyAxisAngle": function applyAxisAngle( a, b ){
    [code]
  },
  "applyEuler": function applyEuler( a ){
    [code]
  },
  "applyMatrix3": function applyMatrix3( a ){
    [code]
  },
  "applyMatrix4": function applyMatrix4( a ){
    [code]
  },
  "applyProjection": function applyProjection( a ){
    [code]
  },
  "applyQuaternion": function applyQuaternion( a ){
    [code]
  },
  "ceil": function ceil(){
    [code]
  },
  "changeBasis": function changeBasis( a, b, c, d ){
    [code]
  },
  "clamp": function clamp( a, b ){
    [code]
  },
  "clampLength": function clampLength( a, b ){
    [code]
  },
  "clampScalar": function clampScalar( a, b ){
    [code]
  },
  "clone": function clone(){
    [code]
  },
  "copy": function copy( a ){
    [code]
  },
  "cross": function cross( a, b ){
    [code]
  },
  "crossVectors": function crossVectors( a, b ){
    [code]
  },
  "distanceTo": function distanceTo( a ){
    [code]
  },
  "distanceToManhattan": function distanceToManhattan( a ){
    [code]
  },
  "distanceToSquared": function distanceToSquared( a ){
    [code]
  },
  "divide": function divide( a ){
    [code]
  },
  "divideScalar": function divideScalar( a ){
    [code]
  },
  "dot": function dot( a ){
    [code]
  },
  "equals": function equals( a ){
    [code]
  },
  "floor": function floor(){
    [code]
  },
  "fromArray": function fromArray( a, b ){
    [code]
  },
  "fromAttribute": function fromAttribute( a, b, c ){
    [code]
  },
  "fromBufferAttribute": function fromBufferAttribute( a, b, c ){
    [code]
  },
  "getColumnFromMatrix": function getColumnFromMatrix( a, b ){
    [code]
  },
  "getComponent": function getComponent( a ){
    [code]
  },
  "getPositionFromMatrix": function getPositionFromMatrix( a ){
    [code]
  },
  "getScaleFromMatrix": function getScaleFromMatrix( a ){
    [code]
  },
  "isVector3": true,
  "length": function length(){
    [code]
  },
  "lengthManhattan": function lengthManhattan(){
    [code]
  },
  "lengthSq": function lengthSq(){
    [code]
  },
  "lerp": function lerp( a, b ){
    [code]
  },
  "lerpVectors": function lerpVectors( a, b, c ){
    [code]
  },
  "manhattanDistanceTo": function manhattanDistanceTo( a ){
    [code]
  },
  "manhattanLength": function manhattanLength(){
    [code]
  },
  "max": function max( a ){
    [code]
  },
  "min": function min( a ){
    [code]
  },
  "multiply": function multiply( a, b ){
    [code]
  },
  "multiplyScalar": function multiplyScalar( a ){
    [code]
  },
  "multiplyVectors": function multiplyVectors( a, b ){
    [code]
  },
  "negate": function negate(){
    [code]
  },
  "normalize": function normalize(){
    [code]
  },
  "project": function project( a ){
    [code]
  },
  "projectOnPlane": function projectOnPlane( a ){
    [code]
  },
  "projectOnVector": function projectOnVector( a ){
    [code]
  },
  "reflect": function reflect( a ){
    [code]
  },
  "rejectOnVector": function rejectOnVector( a ){
    [code]
  },
  "round": function round(){
    [code]
  },
  "roundToZero": function roundToZero(){
    [code]
  },
  "set": function set( a, b, c ){
    [code]
  },
  "setComponent": function setComponent( a, b ){
    [code]
  },
  "setEulerFromQuaternion": function setEulerFromQuaternion(){
    [code]
  },
  "setEulerFromRotationMatrix": function setEulerFromRotationMatrix(){
    [code]
  },
  "setFromCylindrical": function setFromCylindrical( a ){
    [code]
  },
  "setFromMatrixColumn": function setFromMatrixColumn( a, b ){
    [code]
  },
  "setFromMatrixPosition": function setFromMatrixPosition( a ){
    [code]
  },
  "setFromMatrixScale": function setFromMatrixScale( a ){
    [code]
  },
  "setFromSpherical": function setFromSpherical( a ){
    [code]
  },
  "setLength": function setLength( a ){
    [code]
  },
  "setScalar": function setScalar( a ){
    [code]
  },
  "setX": function setX( a ){
    [code]
  },
  "setY": function setY( a ){
    [code]
  },
  "setZ": function setZ( a ){
    [code]
  },
  "sub": function sub( a, b ){
    [code]
  },
  "subScalar": function subScalar( a ){
    [code]
  },
  "subVectors": function subVectors( a, b ){
    [code]
  },
  "toArray": function toArray( a, b ){
    [code]
  },
  "transformDirection": function transformDirection( a ){
    [code]
  },
  "unproject": function unproject( a ){
    [code]
  },
  "x": 2,
  "y": 3,
  "z": 4
}

Result: 	

{
  "add": function add( a, b ){
    [code]
  },
  "addScalar": function addScalar( a ){
    [code]
  },
  "addScaledVector": function addScaledVector( a, b ){
    [code]
  },
  "addVectors": function addVectors( a, b ){
    [code]
  },
  "angleTo": function angleTo( a ){
    [code]
  },
  "applyAxisAngle": function applyAxisAngle( a, b ){
    [code]
  },
  "applyEuler": function applyEuler( a ){
    [code]
  },
  "applyMatrix3": function applyMatrix3( a ){
    [code]
  },
  "applyMatrix4": function applyMatrix4( a ){
    [code]
  },
  "applyProjection": function applyProjection( a ){
    [code]
  },
  "applyQuaternion": function applyQuaternion( a ){
    [code]
  },
  "ceil": function ceil(){
    [code]
  },
  "changeBasis": function changeBasis( a, b, c, d ){
    [code]
  },
  "clamp": function clamp( a, b ){
    [code]
  },
  "clampLength": function clampLength( a, b ){
    [code]
  },
  "clampScalar": function clampScalar( a, b ){
    [code]
  },
  "clone": function clone(){
    [code]
  },
  "copy": function copy( a ){
    [code]
  },
  "cross": function cross( a, b ){
    [code]
  },
  "crossVectors": function crossVectors( a, b ){
    [code]
  },
  "distanceTo": function distanceTo( a ){
    [code]
  },
  "distanceToManhattan": function distanceToManhattan( a ){
    [code]
  },
  "distanceToSquared": function distanceToSquared( a ){
    [code]
  },
  "divide": function divide( a ){
    [code]
  },
  "divideScalar": function divideScalar( a ){
    [code]
  },
  "dot": function dot( a ){
    [code]
  },
  "equals": function equals( a ){
    [code]
  },
  "floor": function floor(){
    [code]
  },
  "fromArray": function fromArray( a, b ){
    [code]
  },
  "fromAttribute": function fromAttribute( a, b, c ){
    [code]
  },
  "fromBufferAttribute": function fromBufferAttribute( a, b, c ){
    [code]
  },
  "getColumnFromMatrix": function getColumnFromMatrix( a, b ){
    [code]
  },
  "getComponent": function getComponent( a ){
    [code]
  },
  "getPositionFromMatrix": function getPositionFromMatrix( a ){
    [code]
  },
  "getScaleFromMatrix": function getScaleFromMatrix( a ){
    [code]
  },
  "isVector3": true,
  "length": function length(){
    [code]
  },
  "lengthManhattan": function lengthManhattan(){
    [code]
  },
  "lengthSq": function lengthSq(){
    [code]
  },
  "lerp": function lerp( a, b ){
    [code]
  },
  "lerpVectors": function lerpVectors( a, b, c ){
    [code]
  },
  "manhattanDistanceTo": function manhattanDistanceTo( a ){
    [code]
  },
  "manhattanLength": function manhattanLength(){
    [code]
  },
  "max": function max( a ){
    [code]
  },
  "min": function min( a ){
    [code]
  },
  "multiply": function multiply( a, b ){
    [code]
  },
  "multiplyScalar": function multiplyScalar( a ){
    [code]
  },
  "multiplyVectors": function multiplyVectors( a, b ){
    [code]
  },
  "negate": function negate(){
    [code]
  },
  "normalize": function normalize(){
    [code]
  },
  "project": function project( a ){
    [code]
  },
  "projectOnPlane": function projectOnPlane( a ){
    [code]
  },
  "projectOnVector": function projectOnVector( a ){
    [code]
  },
  "reflect": function reflect( a ){
    [code]
  },
  "rejectOnVector": function rejectOnVector( a ){
    [code]
  },
  "round": function round(){
    [code]
  },
  "roundToZero": function roundToZero(){
    [code]
  },
  "set": function set( a, b, c ){
    [code]
  },
  "setComponent": function setComponent( a, b ){
    [code]
  },
  "setEulerFromQuaternion": function setEulerFromQuaternion(){
    [code]
  },
  "setEulerFromRotationMatrix": function setEulerFromRotationMatrix(){
    [code]
  },
  "setFromCylindrical": function setFromCylindrical( a ){
    [code]
  },
  "setFromMatrixColumn": function setFromMatrixColumn( a, b ){
    [code]
  },
  "setFromMatrixPosition": function setFromMatrixPosition( a ){
    [code]
  },
  "setFromMatrixScale": function setFromMatrixScale( a ){
    [code]
  },
  "setFromSpherical": function setFromSpherical( a ){
    [code]
  },
  "setLength": function setLength( a ){
    [code]
  },
  "setScalar": function setScalar( a ){
    [code]
  },
  "setX": function setX( a ){
    [code]
  },
  "setY": function setY( a ){
    [code]
  },
  "setZ": function setZ( a ){
    [code]
  },
  "sub": function sub( a, b ){
    [code]
  },
  "subScalar": function subScalar( a ){
    [code]
  },
  "subVectors": function subVectors( a, b ){
    [code]
  },
  "toArray": function toArray( a, b ){
    [code]
  },
  "transformDirection": function transformDirection( a ){
    [code]
  },
  "unproject": function unproject( a ){
    [code]
  },
  "x": 1,
  "y": 2,
  "z": 3
}

Diff: 	

{
  "add": function add( a, b ){
    [code]
  },
  "addScalar": function addScalar( a ){
    [code]
  },
  "addScaledVector": function addScaledVector( a, b ){
    [code]
  },
  "addVectors": function addVectors( a, b ){
    [code]
  },
  "angleTo": function angleTo( a ){
    [code]
  },
  "applyAxisAngle": function applyAxisAngle( a, b ){
    [code]
  },
  "applyEuler": function applyEuler( a ){
    [code]
  },
  "applyMatrix3": function applyMatrix3( a ){
    [code]
  },
  "applyMatrix4": function applyMatrix4( a ){
    [code]
  },
  "applyProjection": function applyProjection( a ){
    [code]
  },
  "applyQuaternion": function applyQuaternion( a ){
    [code]
  },
  "ceil": function ceil(){
    [code]
  },
  "changeBasis": function changeBasis( a, b, c, d ){
    [code]
  },
  "clamp": function clamp( a, b ){
    [code]
  },
  "clampLength": function clampLength( a, b ){
    [code]
  },
  "clampScalar": function clampScalar( a, b ){
    [code]
  },
  "clone": function clone(){
    [code]
  },
  "copy": function copy( a ){
    [code]
  },
  "cross": function cross( a, b ){
    [code]
  },
  "crossVectors": function crossVectors( a, b ){
    [code]
  },
  "distanceTo": function distanceTo( a ){
    [code]
  },
  "distanceToManhattan": function distanceToManhattan( a ){
    [code]
  },
  "distanceToSquared": function distanceToSquared( a ){
    [code]
  },
  "divide": function divide( a ){
    [code]
  },
  "divideScalar": function divideScalar( a ){
    [code]
  },
  "dot": function dot( a ){
    [code]
  },
  "equals": function equals( a ){
    [code]
  },
  "floor": function floor(){
    [code]
  },
  "fromArray": function fromArray( a, b ){
    [code]
  },
  "fromAttribute": function fromAttribute( a, b, c ){
    [code]
  },
  "fromBufferAttribute": function fromBufferAttribute( a, b, c ){
    [code]
  },
  "getColumnFromMatrix": function getColumnFromMatrix( a, b ){
    [code]
  },
  "getComponent": function getComponent( a ){
    [code]
  },
  "getPositionFromMatrix": function getPositionFromMatrix( a ){
    [code]
  },
  "getScaleFromMatrix": function getScaleFromMatrix( a ){
    [code]
  },
  "isVector3": true,
  "length": function length(){
    [code]
  },
  "lengthManhattan": function lengthManhattan(){
    [code]
  },
  "lengthSq": function lengthSq(){
    [code]
  },
  "lerp": function lerp( a, b ){
    [code]
  },
  "lerpVectors": function lerpVectors( a, b, c ){
    [code]
  },
  "manhattanDistanceTo": function manhattanDistanceTo( a ){
    [code]
  },
  "manhattanLength": function manhattanLength(){
    [code]
  },
  "max": function max( a ){
    [code]
  },
  "min": function min( a ){
    [code]
  },
  "multiply": function multiply( a, b ){
    [code]
  },
  "multiplyScalar": function multiplyScalar( a ){
    [code]
  },
  "multiplyVectors": function multiplyVectors( a, b ){
    [code]
  },
  "negate": function negate(){
    [code]
  },
  "normalize": function normalize(){
    [code]
  },
  "project": function project( a ){
    [code]
  },
  "projectOnPlane": function projectOnPlane( a ){
    [code]
  },
  "projectOnVector": function projectOnVector( a ){
    [code]
  },
  "reflect": function reflect( a ){
    [code]
  },
  "rejectOnVector": function rejectOnVector( a ){
    [code]
  },
  "round": function round(){
    [code]
  },
  "roundToZero": function roundToZero(){
    [code]
  },
  "set": function set( a, b, c ){
    [code]
  },
  "setComponent": function setComponent( a, b ){
    [code]
  },
  "setEulerFromQuaternion": function setEulerFromQuaternion(){
    [code]
  },
  "setEulerFromRotationMatrix": function setEulerFromRotationMatrix(){
    [code]
  },
  "setFromCylindrical": function setFromCylindrical( a ){
    [code]
  },
  "setFromMatrixColumn": function setFromMatrixColumn( a, b ){
    [code]
  },
  "setFromMatrixPosition": function setFromMatrixPosition( a ){
    [code]
  },
  "setFromMatrixScale": function setFromMatrixScale( a ){
    [code]
  },
  "setFromSpherical": function setFromSpherical( a ){
    [code]
  },
  "setLength": function setLength( a ){
    [code]
  },
  "setScalar": function setScalar( a ){
    [code]
  },
  "setX": function setX( a ){
    [code]
  },
  "setY": function setY( a ){
    [code]
  },
  "setZ": function setZ( a ){
    [code]
  },
  "sub": function sub( a, b ){
    [code]
  },
  "subScalar": function subScalar( a ){
    [code]
  },
  "subVectors": function subVectors( a, b ){
    [code]
  },
  "toArray": function toArray( a, b ){
    [code]
  },
  "transformDirection": function transformDirection( a ){
    [code]
  },
  "unproject": function unproject( a ){
    [code]
  },
  "x": 21,
  "y": 32,
  "z": 43
}
</pre>
</details>

**Comment by Arkni** [comment] 2018-08-01 09:34
This looks like a duplicate of #1209

**Comment by loldrup** [comment] 2018-08-01 11:09
It does look like a duplicate of #1209, but, in #1209 I did not demonstrate that the problem is also a problem merely when comparing objects that have the same prototype. In #1209 I only complained about the prototype being shown when just one object had a prototype. I'd say this bug report describes a tighter problem than #1209, if you get what I mean.

In #1209 Krinkle wrote:
"Just for the record, QUnit's deep comparator does not needless follow prototype chains. It does a recursive comparison on each property. Only when a property isn't equal will it traverse the referenced object. This means that prototype chains, naturally, are not followed if they are the same.

However, this issue is specific to the logging of the results once a difference is determined. It seems in that case we always dump the full object, regardless of how deep the comparator had to traverse."

With this bug report I believe to have demonstrated that Krinkle was not right in saying this. We now see that prototype chains are followed even when they are perfectly similar.

**Comment by loldrup** [comment] 2019-10-19 21:45
Is there a realistic hope to have this issue solved?
@Krinkle

**Comment by Krinkle** [comment] 2019-10-20 00:46
The issue seems uncontroversial. I see no opposition here. Just need some help getting it done :)

Limiting the number of lines context in the textual diff makes sense to me. We currently use an old Google library for the diff generating. Perhaps you could take a look at what it supports and what it would take to limit the diff size?

Seehttps://github.com/qunitjs/qunit/blob/2.9.3/reporter/html.js#L795-L848

And https://github.com/qunitjs/qunit/blob/2.9.3/reporter/diff.js

**Comment by Krinkle** [comment] 2019-10-20 00:47
https://github.com/qunitjs/qunit/blob/2.9.3/reporter/html.js#L826-L830

**Comment by loldrup** [comment] 2019-10-20 09:46
I'd love to, but due to health issues, I can only use a computer for short amounts of time during a day. I'd better focus that usage on my actual project, else it'll never get anywhere.

**Comment by Krinkle** [comment] 2020-06-25 02:25
Closing as duplicate of https://github.com/qunitjs/qunit/issues/1209.

**Closed by Krinkle** 2020-06-25 02:25 UTC
Labels: component-reporter, type-enhancement
