### ISSUE TITLE
Regression: Error results shouldn't contain actual/expected

### ISSUE THREAD

**Issue by Krinkle** [qunitjs/qunit#1219] opened 2017-08-12 16:43 UTC
* **QUnit version**: 2.4.0

I believe since QUnit 2.x, there has been a minor change in the shape of the resultInfo object passed to `QUnit.log` handlers. Previously, the `expected` property would not exist if the log entry was the result of catching an exception or some other violation that is not the result if an explicit Assert method call. Typically through `pushFailure`.

However, this has since been normalised, and the object now always gets a default `null` actual/expected.

This is causing odd outputs like the following, which very confusingly claim there was a (seemingly s) assertion where an actual value `null` matched the expected value `null`, despite there having been no such assertion.

Minimal test case:
```
QUnit.test('example', function (assert) {
  assert.ok(true);
  assert.ok(false);
  throw new Error('Rebase');
});
```

HTML reporter (built-in):
<img width="610" alt="screen shot 2017-08-12 at 12 39 56" src="https://user-images.githubusercontent.com/156867/29242441-6138cc62-7f5b-11e7-8b12-496182824238.png">

Command-line output using Karma and karma-qunit:
<img width="873" alt="screen shot 2017-08-12 at 12 40 12" src="https://user-images.githubusercontent.com/156867/29242442-6bccef82-7f5b-11e7-8da7-98f1b6502e57.png">

I thought at first that maybe the `info.result` property being `false` is indicative of a general failure, but that's not the case given it is also false for a regular assertion failure.

Looking more closely at the actual code, I see that both our HTML reporter, as well as the karma-qunit formatter, make the same (now incorrect) assumption that the `expected` properly may not exist.

<https://github.com/qunitjs/qunit/blob/2.4.0/reporter/html.js#L764-L775>
<https://github.com/karma-runner/karma-qunit/blob/52eec0e8bc6d4f854de9cae2ff2213e2261e1a5b/src/adapter.js#L83>

/cc @jdforrester

**Comment by trentmwillis** [comment] 2017-08-15 01:25
I believe this is a duplicate of https://github.com/qunitjs/qunit/issues/1166, which I recently noted is a regression and should be fixed.

**Closed** 2017-08-16 05:56 UTC
Labels: api, bug, reporter
