### ISSUE TITLE
Test timeout with async/done can lead to unrelated error

### ISSUE THREAD

**Issue by smcclure15** [qunitjs/qunit#1592] opened 2021-04-15 14:47 UTC
Run on latest QUnit 2.15.0 via CLI:

```js
QUnit.test( "demo", assert => {
	assert.timeout( 10 );
	const done = assert.async();
	assert.true( true );
	setTimeout( done, 20 );
} );
```

The first half of the run looks good:
```
TAP version 13
not ok 1 demo
  ---
  message: Test took longer than 10ms; test timed out.
  severity: failed
  actual  : null
  expected: undefined
  stack: |
        at listOnTimeout (internal/timers.js:554:17)
        at processTimers (internal/timers.js:497:7)
  ...
1..1
# pass 0
# skip 0
# todo 0
# fail 1
```
It's correctly reported via the TAP output, but the process continues, and that "done" is finally executed, which throws this:
```
/<SNIP>/qunit.js:2312
        if (module.hooks[handler].length) {
                                  ^

TypeError: Cannot read property 'length' of undefined
    at processHooks (/<SNIP>/qunit.js:2312:35)
    <SNIP>
```

This causes the exit code to be not a 1 or 0, but actually 7. We should be able to provide a cleaner message here.

This is related to #1432, where if you have a test that follows this, and the done is executed inside _that_ test, then you see the error "assert.async callback called after test finished." (with an exit code of 1).

**Comment by Krinkle** [comment] 2021-04-15 17:51
I think this is a duplicate of https://github.com/qunitjs/qunit/issues/1377. #1432 is similar indeed, but I think #1377 is identical, right?

**Comment by smcclure15** [comment] 2021-04-15 18:23
Agreed, looks identical to #1377 - thanks!

**Closed** 2021-04-15 18:25 UTC
Labels: Component: Core, Status: Duplicate, Type: Problem
