### ISSUE TITLE
Changing QUnit.config.testId has no effect.

### ISSUE THREAD

**Issue by averydev** [qunitjs/qunit#1331] opened 2018-11-29 06:05 UTC
## Tell us about your runtime:

* **QUnit version**:2.7.0
* **What environment are you running QUnit in? (e.g., browser, Node)**: browser
* **How are you running QUnit? (e.g., script, testem, Grunt)**: ember-qunit

## What are you trying to do?
I'm attempting to change the current test on the fly by clicking a button on the testing page. 

Code that reproduces the problem:

```js
const testId = `abc`; //where abc is a valid testId
window.QUnit.config.testId = [testId];
```
This has no effect. 
The documentation says:

```QUnit.config.testId (array) | default: undefined
This property allows QUnit to run specific tests identified by the hashed version of their module name
and test name. You can specify one or multiple tests to run.
```

I have the same experience with all of the QUnit.config properties, so I'm probably just missing a step, but I have gone through the docs quite carefully and can't figure out what I would need to do to have this work like the docs describe. 

## What did you expect to happen?

I expect the specified test to run. 

## What actually happened?
No apparent change in behavior. 

The only way i am able to have any effect on the tests that run is by directly changing the window.location, which causes a page refresh.

**Comment by Krinkle** [comment] 2020-08-30 02:13
Closing since this generally works and is also confirmed through tests and in general use. Feel free to ping again or file a new issue if you encounter this still on the latest stable.

**Closed by Krinkle** 2020-08-30 02:13 UTC
Labels: Category: API, Status: Stalled, Type: Problem
