### ISSUE TITLE
moduleDone called before module is done

### ISSUE THREAD

**Issue by fcarstens** [qunitjs/qunit#830] opened 2015-06-29 08:16 UTC
##### Steps to reproduce the problem:
1. Write two modules. The first module contains two tests. One of the tests fails. The second module contains a single test that fails.
2. Log QUnit.moduleDone events
3. Run the programm twice.
##### What is the expected behavoir?

We expect to have two moduleDone events in both runs.
##### What went wrong?

We have three moduleDone events in the second run.
##### Any other comments?

`QUnit.config.reorder = false` gives us two moduleDone events constantly.

Here is a [JS Bin demo](http://jsbin.com/cizinoludu/1/edit?html,js,console,output)

**Comment by leobalter** [comment] 2015-06-29 15:16
This is the same behavior at least from QUnit 1.9.0 until the current build.

Every suite rerun will execute first the tests that previously failed. `QUnit.moduleDone` is being triggered prematurely as the module got split. 

This might be interpreted as a end of the module for those failing tests and than the module will be called again for the remaining tests on it. And this might affect other reporters as a regression.

Although, it's good to keep this open so we can decide about this for QUnit 2.0.0. Until a next major version, `QUnt.config.reorder = false` is the best option to prevent this behavior.

**Comment by jzaefferer** [comment] 2015-08-11 21:11
As discussed in the jsreporters repo, I consider this a bug, not an enhancement. Similar to the html reporter keeping the order of the tests as defined (not as executed), the events should also stay in that order.

**Comment by leobalter** [comment] 2015-08-11 21:44
I don't see this as an enhancement, I don't even know what I was thinking when I set this label.

**Comment by mixed** [comment] 2015-12-18 09:22
@jzaefferer @leobalter 

I have invested it. This issues is related to config.reorder. Setting config.reorder QUnit run first failed test. Although Tests was same module Tests did not call same group like below case.
```
module1
	- test1 (fail)
	- test2 (true)
module2
	- test1 (fail)
```
First Time order is `module1-test1 -> module1-test2 -> module2-test1`. Next Time order is `module1-test2 -> module2-test1 -> module1-test1` becacuse `config.reorder`.

QUnit has a problem in this case. When QUnit is module change to another module QUnit have triggered `moduleDone` event. [link](https://github.com/jquery/qunit/blob/master/src/test.js#L56) So. Above case have occurred to trigger `moduleDone` event.
```
`module1-test2` -> module1
	(changed module. so fired moduleDone)
`module2-test1` -> module2 
	(changed module. so fired moduleDone)
`module1-test1` -> module1 
	(end. so fire moduleDone)
```

I think that I suggest to two options in this case
1. should be change test in same module.
2. save module status info in config(or somewhere)

I have some questions.
1. What option would you suggest for me?
	- If QUnit should be support to `config.reorder` option I like 2.
2. I think that All options change to many codes. So Could i work it?

**Comment by trentmwillis** [comment] 2016-03-02 06:51
I would definitely consider this a bug; due in large part to [this logic](https://github.com/jquery/qunit/blob/master/src/test.js#L48-L49) that fires the `moduleDone` event whenever the current module changes (not necessarily when the module has ended).

We should change that firing condition to check that all tests for the module have run. However, there is currently no way to do that, but it'll be super easy to implement once #919 has been merged as it also requires checking if all tests for a given module have run.

**Comment by leobalter** [comment] 2017-03-31 04:40
This seems to be fixed now. I've got the original JSBin example and tried it with a [recent version](http://jsbin.com/riborakelu/edit?html,js,console,output).

**Closed by leobalter** 2017-03-31 04:40 UTC
Labels: bug, help wanted
